window.jQuery = $ = require('./multikart/jquery-3.3.1.min')

require('./multikart/bootstrap.bundle.min')
window.feather =require('./multikart/icons/feather-icon/feather.min')
require('./multikart/sidebar-menu')
window.Chartist = require('./multikart/chart/chartist/chartist')
window.Chart =  require('./multikart/chart/chartjs/chart.min')
require('./multikart/lazysizes.min')
require('./multikart/icons/feather-icon/feather-icon')

require('./multikart/prism/prism.min.js')
window.ClipboardJS =  require('./multikart/clipboard/clipboard.min.js')
require('./multikart/custom-card/custom-card')
require('./multikart/counter/jquery.waypoints.min')
require('./multikart/counter/jquery.counterup.min')
require('./multikart/counter/counter-custom')
require('./multikart/chart/peity-chart/peity.jquery')
window.sparkline = require('./multikart/chart/sparkline/sparkline')
require('./multikart/admin-customizer')
require('./multikart/dashboard/default')
require('./multikart/chat-menu')
require('./multikart/height-equal')
require('./multikart/admin-script')
