window.jQuery = window.$ = require('jquery')
require('./multikart/jquery-ui.min.js')
require('./multikart/jquery.exitintent')
require('./multikart/exit')
require('./multikart/slick')
require('./multikart/menu')
require('./multikart/lazysizes.min')
require('./multikart/bootstrap.bundle.min')
require('./multikart/bootstrap-notify.min')
require('./multikart/fly-cart')
require('./multikart/theme-setting')
require('./multikart/script')
